"""Export the method registry for the application.

The frontend cannot import Python, so without this it would need its own copy of which
methods exist, when they apply, and why — and two copies of the same table drift apart,
usually at the worst moment (D-024).

Exporting rather than duplicating also enforces the rule the whole project runs on: the
tool only offers what the study evaluated.

    uv run python scripts/export_methods.py
"""

from __future__ import annotations

import json

from mlsandbox.config import PROJECT_ROOT
from mlsandbox.methods import METHODS, SCORING

EXPORT_PATH = PROJECT_ROOT / "config" / "methods.json"

FIELD_DOCS = {
    "name": "Stable identifier. What the study records and the API accepts.",
    "label": "Human-readable name, shown in the interface.",
    "family": (
        "The ISLR family. The recommender reasons in families, so coverage matters more "
        "than count."
    ),
    "tasks": (
        "Which prediction types this method applies to. A method absent from a task is "
        "shown disabled with its reason, never hidden (FR-8.3)."
    ),
    "needs_scaling": (
        "Whether the result depends on feature units. Distance-based, regularised and "
        "gradient-based methods do; trees do not."
    ),
    "handles_nan": (
        "Whether the method accepts missing values without imputation. Verified against "
        "the installed scikit-learn by the test suite, not merely declared."
    ),
    "tuning": (
        "`internal-cv` where the method has no meaningful default value and shipping it "
        "untuned would measure an arbitrary choice rather than the method (D-019)."
    ),
    "implementation": (
        "`sklearn`, or `r` for the two methods whose reference implementations live there "
        "(D-020). The application offers both; only the backend differs."
    ),
    "rationale": (
        "What this method represents on the bias-variance and interpretability axes. The "
        "recommender's explanations are built from this."
    ),
    "incompatibility": (
        "Per task, why the method does not apply, in words a user without ML background "
        "can act on. Absent where the method applies."
    ),
}


def build() -> dict:
    return {
        "_fields": FIELD_DOCS,
        "_note": (
            "Generated by scripts/export_methods.py from the registry in "
            "src/mlsandbox/methods.py. Do not edit by hand: the study and the application "
            "read the same table so they cannot disagree about which methods exist."
        ),
        "scoring": SCORING,
        "methods": [
            {
                **method.model_dump(mode="json"),
                "incompatibility": {
                    task: method.incompatibility_reason(task)  # type: ignore[arg-type]
                    for task in ("classification", "regression")
                    if method.incompatibility_reason(task)  # type: ignore[arg-type]
                },
            }
            for method in METHODS.values()
        ],
    }


def main() -> int:
    export = build()
    EXPORT_PATH.write_text(json.dumps(export, indent=2) + "\n", encoding="utf-8")

    by_family: dict[str, list[str]] = {}
    for method in export["methods"]:
        by_family.setdefault(method["family"], []).append(method["name"])

    print(f"{len(export['methods'])} methods, {len(by_family)} families")
    for family, names in sorted(by_family.items()):
        print(f"  {family:20} {', '.join(names)}")
    print(f"\nwritten to {EXPORT_PATH.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
